-- MySQL Script generated by MySQL Workbench
-- Thu Mar  2 11:03:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alunos` (
  `idAlunos` INT NOT NULL AUTO_INCREMENT,
  `Alunos_nome` TINYTEXT CHARACTER SET 'utf8' NOT NULL,
  `Alunos_sexo` TINYTEXT NOT NULL,
  `endereço` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `Telefone` INT NOT NULL,
  `e-mail` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `Responsavel` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `Nascimento` DATE NOT NULL,
  PRIMARY KEY (`idAlunos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professores` (
  `idProfessores` INT NOT NULL AUTO_INCREMENT,
  `Professor_nome` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `Professor_sexo` VARCHAR(45) BINARY NULL,
  `especialidade-1` VARCHAR(45) CHARACTER SET 'utf8' BINARY NULL,
  `especialidade-2` VARCHAR(45) CHARACTER SET 'utf8' BINARY NULL,
  PRIMARY KEY (`idProfessores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `idDisciplinas` INT NOT NULL,
  `Disciplinas_nome` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `Professores_idProfessores` INT NOT NULL,
  `Professores_Professor_nome` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`idDisciplinas`, `Professores_idProfessores`, `Professores_Professor_nome`),
  INDEX `fk_Disciplinas_Professores1_idx` (`Professores_idProfessores` ASC, `Professores_Professor_nome` ASC) VISIBLE,
  CONSTRAINT `fk_Disciplinas_Professores1`
    FOREIGN KEY (`Professores_idProfessores` , `Professores_Professor_nome`)
    REFERENCES `mydb`.`Professores` (`idProfessores` , `Professor_nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turma` (
  `idTurma` INT NOT NULL,
  `Turno` VARCHAR(45) NOT NULL,
  `Alunos_idAlunos` INT NOT NULL,
  `Alunos_Alunos_nome` VARCHAR(45) NOT NULL,
  `Disciplinas_idDisciplinas` INT NOT NULL,
  `Disciplinas_Disciplinas_nome` VARCHAR(45) NOT NULL,
  `Disciplinas_Professores_idProfessores` INT NOT NULL,
  `Disciplinas_Professores_Professor_nome` VARCHAR(45) NOT NULL,
  `Sala` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTurma`, `Turno`, `Alunos_idAlunos`, `Alunos_Alunos_nome`, `Disciplinas_idDisciplinas`, `Disciplinas_Disciplinas_nome`, `Disciplinas_Professores_idProfessores`, `Disciplinas_Professores_Professor_nome`),
  INDEX `fk_Turma_Alunos_idx` (`Alunos_idAlunos` ASC, `Alunos_Alunos_nome` ASC) VISIBLE,
  INDEX `fk_Turma_Disciplinas1_idx` (`Disciplinas_idDisciplinas` ASC, `Disciplinas_Disciplinas_nome` ASC, `Disciplinas_Professores_idProfessores` ASC, `Disciplinas_Professores_Professor_nome` ASC) VISIBLE,
  CONSTRAINT `fk_Turma_Alunos`
    FOREIGN KEY (`Alunos_idAlunos` , `Alunos_Alunos_nome`)
    REFERENCES `mydb`.`Alunos` (`idAlunos` , `Alunos_nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_Disciplinas1`
    FOREIGN KEY (`Disciplinas_idDisciplinas` , `Disciplinas_Disciplinas_nome` , `Disciplinas_Professores_idProfessores` , `Disciplinas_Professores_Professor_nome`)
    REFERENCES `mydb`.`Curso` (`idDisciplinas` , `Disciplinas_nome` , `Professores_idProfessores` , `Professores_Professor_nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
